[crawler]
site_depth = 10
run_interval = "30m"

[server]
port = 3321
hostname = "0.0.0.0"
database_location = "/var/badger"
max_payload_size = 256

[server.ratelimits]
allowed_requests = 200
reset_duration = 300000
